install.packages('devtools')
devtools::install_github('ohdsi/DatabaseConnector')
devtools::install_github('cran/raster', ref='2.6-7')
install.packages("DCluster")
install.packages("maps")
install.packages("mapdata")
install.packages("mapproj")
install.packages("leaflet")
install.packages("ggmap")
install.packages("dplyr")
install.packages("sqldf")
install.packages("shiny")
install.packages("bindrcpp")
install.packages("pkgconfig")
install.packages("shinyjs")
install.packages("shinydashboard")
install.packages("maptools")
install.packages("SpatialEpi")
install.packages("lubridate")
install.packages("rgdal")
install.packages("gpclib")
install.packages("rgeos")
install.packages("RColorBrewer")
install.packages("DT")
install.packages("leafpop")
install.packages('openssl')
install.packages('jose')

